/* 
 * YouLend Third Party Pre Qualification API
 *
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using YL.Web.Api.ThirdParty.Prequalification.Client.Client;
using YL.Web.Api.ThirdParty.Prequalification.Client.Api;
using YL.Web.Api.ThirdParty.Prequalification.Client.Model;

namespace YL.Web.Api.ThirdParty.Prequalification.Client.Test
{
    /// <summary>
    ///  Class for testing RequestsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RequestsApiTests : IDisposable
    {
        private RequestsApi instance;

        public RequestsApiTests()
        {
            instance = new RequestsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RequestsApi
            //Assert.IsType(typeof(RequestsApi), instance, "instance is a RequestsApi");
        }

        
        /// <summary>
        /// Test RequestsPost
        /// </summary>
        [Fact]
        public void RequestsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apiVersion = null;
            //PreQualificationModel preQualificationModel = null;
            //var response = instance.RequestsPost(apiVersion, preQualificationModel);
            //Assert.IsType<PreQualificationResultDocument> (response, "response is PreQualificationResultDocument");
        }
        
    }

}
