/* 
 * YouLend Third Party Pre Qualification API
 *
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = YL.Web.Api.ThirdParty.Prequalification.Client.Client.OpenAPIDateConverter;

namespace YL.Web.Api.ThirdParty.Prequalification.Client.Model
{
    /// <summary>
    /// PaymentDataRowModel
    /// </summary>
    [DataContract]
    public partial class PaymentDataRowModel :  IEquatable<PaymentDataRowModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentDataRowModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PaymentDataRowModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentDataRowModel" /> class.
        /// </summary>
        /// <param name="paymentDate">paymentDate (required).</param>
        /// <param name="amount">amount (required).</param>
        /// <param name="currencyISOCode">currencyISOCode (required).</param>
        public PaymentDataRowModel(DateTime paymentDate = default(DateTime), double amount = default(double), string currencyISOCode = default(string))
        {
            // to ensure "paymentDate" is required (not null)
            if (paymentDate == null)
            {
                throw new InvalidDataException("paymentDate is a required property for PaymentDataRowModel and cannot be null");
            }
            else
            {
                this.PaymentDate = paymentDate;
            }

            // to ensure "amount" is required (not null)
            if (amount == null)
            {
                throw new InvalidDataException("amount is a required property for PaymentDataRowModel and cannot be null");
            }
            else
            {
                this.Amount = amount;
            }

            // to ensure "currencyISOCode" is required (not null)
            if (currencyISOCode == null)
            {
                throw new InvalidDataException("currencyISOCode is a required property for PaymentDataRowModel and cannot be null");
            }
            else
            {
                this.CurrencyISOCode = currencyISOCode;
            }

        }
        
        /// <summary>
        /// Gets or Sets PaymentDate
        /// </summary>
        [DataMember(Name="paymentDate", EmitDefaultValue=false)]
        public DateTime PaymentDate { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public double Amount { get; set; }

        /// <summary>
        /// Gets or Sets CurrencyISOCode
        /// </summary>
        [DataMember(Name="currencyISOCode", EmitDefaultValue=false)]
        public string CurrencyISOCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentDataRowModel {\n");
            sb.Append("  PaymentDate: ").Append(PaymentDate).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  CurrencyISOCode: ").Append(CurrencyISOCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PaymentDataRowModel);
        }

        /// <summary>
        /// Returns true if PaymentDataRowModel instances are equal
        /// </summary>
        /// <param name="input">Instance of PaymentDataRowModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentDataRowModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PaymentDate == input.PaymentDate ||
                    (this.PaymentDate != null &&
                    this.PaymentDate.Equals(input.PaymentDate))
                ) && 
                (
                    this.Amount == input.Amount ||
                    this.Amount.Equals(input.Amount)
                ) && 
                (
                    this.CurrencyISOCode == input.CurrencyISOCode ||
                    (this.CurrencyISOCode != null &&
                    this.CurrencyISOCode.Equals(input.CurrencyISOCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PaymentDate != null)
                    hashCode = hashCode * 59 + this.PaymentDate.GetHashCode();
                hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.CurrencyISOCode != null)
                    hashCode = hashCode * 59 + this.CurrencyISOCode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Amount (double) minimum
            if(this.Amount < (double)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Amount, must be a value greater than or equal to 0.", new [] { "Amount" });
            }

            // CurrencyISOCode (string) minLength
            if(this.CurrencyISOCode != null && this.CurrencyISOCode.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CurrencyISOCode, length must be greater than 1.", new [] { "CurrencyISOCode" });
            }

            yield break;
        }
    }

}
