/* 
 * YouLend Third Party Pre Qualification API
 *
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using YL.Web.Api.ThirdParty.Prequalification.Client.Client;
using YL.Web.Api.ThirdParty.Prequalification.Client.Model;

namespace YL.Web.Api.ThirdParty.Prequalification.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRequestsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Initiates a prequalification of a merchant for a loan. It will use as much data as it can to do the analysis  so the more data provided the more accurate the result
        /// </summary>
        /// <remarks>
        /// Can add sample as an example here
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Prequalification.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="preQualificationModel"> (optional)</param>
        /// <returns>PreQualificationResultDocument</returns>
        PreQualificationResultDocument RequestsPost (string apiVersion = default(string), PreQualificationModel preQualificationModel = default(PreQualificationModel));

        /// <summary>
        /// Initiates a prequalification of a merchant for a loan. It will use as much data as it can to do the analysis  so the more data provided the more accurate the result
        /// </summary>
        /// <remarks>
        /// Can add sample as an example here
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Prequalification.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="preQualificationModel"> (optional)</param>
        /// <returns>ApiResponse of PreQualificationResultDocument</returns>
        ApiResponse<PreQualificationResultDocument> RequestsPostWithHttpInfo (string apiVersion = default(string), PreQualificationModel preQualificationModel = default(PreQualificationModel));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRequestsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Initiates a prequalification of a merchant for a loan. It will use as much data as it can to do the analysis  so the more data provided the more accurate the result
        /// </summary>
        /// <remarks>
        /// Can add sample as an example here
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Prequalification.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="preQualificationModel"> (optional)</param>
        /// <returns>Task of PreQualificationResultDocument</returns>
        System.Threading.Tasks.Task<PreQualificationResultDocument> RequestsPostAsync (string apiVersion = default(string), PreQualificationModel preQualificationModel = default(PreQualificationModel));

        /// <summary>
        /// Initiates a prequalification of a merchant for a loan. It will use as much data as it can to do the analysis  so the more data provided the more accurate the result
        /// </summary>
        /// <remarks>
        /// Can add sample as an example here
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Prequalification.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="preQualificationModel"> (optional)</param>
        /// <returns>Task of ApiResponse (PreQualificationResultDocument)</returns>
        System.Threading.Tasks.Task<ApiResponse<PreQualificationResultDocument>> RequestsPostAsyncWithHttpInfo (string apiVersion = default(string), PreQualificationModel preQualificationModel = default(PreQualificationModel));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRequestsApi : IRequestsApiSync, IRequestsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RequestsApi : IRequestsApi
    {
        private YL.Web.Api.ThirdParty.Prequalification.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RequestsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RequestsApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RequestsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RequestsApi(String basePath)
        {
            this.Configuration = YL.Web.Api.ThirdParty.Prequalification.Client.Client.Configuration.MergeConfigurations(
                YL.Web.Api.ThirdParty.Prequalification.Client.Client.GlobalConfiguration.Instance,
                new YL.Web.Api.ThirdParty.Prequalification.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new YL.Web.Api.ThirdParty.Prequalification.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new YL.Web.Api.ThirdParty.Prequalification.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = YL.Web.Api.ThirdParty.Prequalification.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RequestsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RequestsApi(YL.Web.Api.ThirdParty.Prequalification.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = YL.Web.Api.ThirdParty.Prequalification.Client.Client.Configuration.MergeConfigurations(
                YL.Web.Api.ThirdParty.Prequalification.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new YL.Web.Api.ThirdParty.Prequalification.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new YL.Web.Api.ThirdParty.Prequalification.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = YL.Web.Api.ThirdParty.Prequalification.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RequestsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public RequestsApi(YL.Web.Api.ThirdParty.Prequalification.Client.Client.ISynchronousClient client,YL.Web.Api.ThirdParty.Prequalification.Client.Client.IAsynchronousClient asyncClient, YL.Web.Api.ThirdParty.Prequalification.Client.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = YL.Web.Api.ThirdParty.Prequalification.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public YL.Web.Api.ThirdParty.Prequalification.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public YL.Web.Api.ThirdParty.Prequalification.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public YL.Web.Api.ThirdParty.Prequalification.Client.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public YL.Web.Api.ThirdParty.Prequalification.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Initiates a prequalification of a merchant for a loan. It will use as much data as it can to do the analysis  so the more data provided the more accurate the result Can add sample as an example here
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Prequalification.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="preQualificationModel"> (optional)</param>
        /// <returns>PreQualificationResultDocument</returns>
        public PreQualificationResultDocument RequestsPost (string apiVersion = default(string), PreQualificationModel preQualificationModel = default(PreQualificationModel))
        {
             YL.Web.Api.ThirdParty.Prequalification.Client.Client.ApiResponse<PreQualificationResultDocument> localVarResponse = RequestsPostWithHttpInfo(apiVersion, preQualificationModel);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Initiates a prequalification of a merchant for a loan. It will use as much data as it can to do the analysis  so the more data provided the more accurate the result Can add sample as an example here
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Prequalification.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="preQualificationModel"> (optional)</param>
        /// <returns>ApiResponse of PreQualificationResultDocument</returns>
        public YL.Web.Api.ThirdParty.Prequalification.Client.Client.ApiResponse< PreQualificationResultDocument > RequestsPostWithHttpInfo (string apiVersion = default(string), PreQualificationModel preQualificationModel = default(PreQualificationModel))
        {
            YL.Web.Api.ThirdParty.Prequalification.Client.Client.RequestOptions localVarRequestOptions = new YL.Web.Api.ThirdParty.Prequalification.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = YL.Web.Api.ThirdParty.Prequalification.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = YL.Web.Api.ThirdParty.Prequalification.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (apiVersion != null)
                localVarRequestOptions.HeaderParameters.Add("api-version", YL.Web.Api.ThirdParty.Prequalification.Client.Client.ClientUtils.ParameterToString(apiVersion)); // header parameter
            localVarRequestOptions.Data = preQualificationModel;

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post< PreQualificationResultDocument >("/Requests", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RequestsPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Initiates a prequalification of a merchant for a loan. It will use as much data as it can to do the analysis  so the more data provided the more accurate the result Can add sample as an example here
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Prequalification.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="preQualificationModel"> (optional)</param>
        /// <returns>Task of PreQualificationResultDocument</returns>
        public async System.Threading.Tasks.Task<PreQualificationResultDocument> RequestsPostAsync (string apiVersion = default(string), PreQualificationModel preQualificationModel = default(PreQualificationModel))
        {
             YL.Web.Api.ThirdParty.Prequalification.Client.Client.ApiResponse<PreQualificationResultDocument> localVarResponse = await RequestsPostAsyncWithHttpInfo(apiVersion, preQualificationModel);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Initiates a prequalification of a merchant for a loan. It will use as much data as it can to do the analysis  so the more data provided the more accurate the result Can add sample as an example here
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Prequalification.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="preQualificationModel"> (optional)</param>
        /// <returns>Task of ApiResponse (PreQualificationResultDocument)</returns>
        public async System.Threading.Tasks.Task<YL.Web.Api.ThirdParty.Prequalification.Client.Client.ApiResponse<PreQualificationResultDocument>> RequestsPostAsyncWithHttpInfo (string apiVersion = default(string), PreQualificationModel preQualificationModel = default(PreQualificationModel))
        {

            YL.Web.Api.ThirdParty.Prequalification.Client.Client.RequestOptions localVarRequestOptions = new YL.Web.Api.ThirdParty.Prequalification.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "application/xml"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (apiVersion != null)
                localVarRequestOptions.HeaderParameters.Add("api-version", YL.Web.Api.ThirdParty.Prequalification.Client.Client.ClientUtils.ParameterToString(apiVersion)); // header parameter
            localVarRequestOptions.Data = preQualificationModel;

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<PreQualificationResultDocument>("/Requests", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RequestsPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
