/* 
 * YouLend Third Party Pre Qualification API
 *
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Prequalification.Client.Api;
using YL.Web.Api.ThirdParty.Prequalification.Client.Model;
using YL.Web.Api.ThirdParty.Prequalification.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Prequalification.Client.Test
{
    /// <summary>
    ///  Class for testing AddressModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddressModel
        //private AddressModel instance;

        public AddressModelTests()
        {
            // TODO uncomment below to create an instance of AddressModel
            //instance = new AddressModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddressModel
        /// </summary>
        [Fact]
        public void AddressModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AddressModel
            //Assert.IsInstanceOfType<AddressModel> (instance, "variable 'instance' is a AddressModel");
        }


        /// <summary>
        /// Test the property 'Line1'
        /// </summary>
        [Fact]
        public void Line1Test()
        {
            // TODO unit test for the property 'Line1'
        }
        /// <summary>
        /// Test the property 'Line2'
        /// </summary>
        [Fact]
        public void Line2Test()
        {
            // TODO unit test for the property 'Line2'
        }
        /// <summary>
        /// Test the property 'Line3'
        /// </summary>
        [Fact]
        public void Line3Test()
        {
            // TODO unit test for the property 'Line3'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'AreaCode'
        /// </summary>
        [Fact]
        public void AreaCodeTest()
        {
            // TODO unit test for the property 'AreaCode'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

    }

}
