/* 
 * YouLend Third Party Pre Qualification API
 *
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Prequalification.Client.Api;
using YL.Web.Api.ThirdParty.Prequalification.Client.Model;
using YL.Web.Api.ThirdParty.Prequalification.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Prequalification.Client.Test
{
    /// <summary>
    ///  Class for testing FinancialDataModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FinancialDataModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FinancialDataModel
        //private FinancialDataModel instance;

        public FinancialDataModelTests()
        {
            // TODO uncomment below to create an instance of FinancialDataModel
            //instance = new FinancialDataModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FinancialDataModel
        /// </summary>
        [Fact]
        public void FinancialDataModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FinancialDataModel
            //Assert.IsInstanceOfType<FinancialDataModel> (instance, "variable 'instance' is a FinancialDataModel");
        }


        /// <summary>
        /// Test the property 'MonthlyCardRevenue'
        /// </summary>
        [Fact]
        public void MonthlyCardRevenueTest()
        {
            // TODO unit test for the property 'MonthlyCardRevenue'
        }
        /// <summary>
        /// Test the property 'PaymentData'
        /// </summary>
        [Fact]
        public void PaymentDataTest()
        {
            // TODO unit test for the property 'PaymentData'
        }
        /// <summary>
        /// Test the property 'MonthlyValueOfPurchaseTransactions'
        /// </summary>
        [Fact]
        public void MonthlyValueOfPurchaseTransactionsTest()
        {
            // TODO unit test for the property 'MonthlyValueOfPurchaseTransactions'
        }
        /// <summary>
        /// Test the property 'PurchaseData'
        /// </summary>
        [Fact]
        public void PurchaseDataTest()
        {
            // TODO unit test for the property 'PurchaseData'
        }
        /// <summary>
        /// Test the property 'MonthlyRevenueFromInvoices'
        /// </summary>
        [Fact]
        public void MonthlyRevenueFromInvoicesTest()
        {
            // TODO unit test for the property 'MonthlyRevenueFromInvoices'
        }
        /// <summary>
        /// Test the property 'InvoiceData'
        /// </summary>
        [Fact]
        public void InvoiceDataTest()
        {
            // TODO unit test for the property 'InvoiceData'
        }

    }

}
