/* 
 * YouLend Third Party Pre Qualification API
 *
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Prequalification.Client.Api;
using YL.Web.Api.ThirdParty.Prequalification.Client.Model;
using YL.Web.Api.ThirdParty.Prequalification.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Prequalification.Client.Test
{
    /// <summary>
    ///  Class for testing LoanOptionDocument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoanOptionDocumentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoanOptionDocument
        //private LoanOptionDocument instance;

        public LoanOptionDocumentTests()
        {
            // TODO uncomment below to create an instance of LoanOptionDocument
            //instance = new LoanOptionDocument();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoanOptionDocument
        /// </summary>
        [Fact]
        public void LoanOptionDocumentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanOptionDocument
            //Assert.IsInstanceOfType<LoanOptionDocument> (instance, "variable 'instance' is a LoanOptionDocument");
        }


        /// <summary>
        /// Test the property 'FundedAmount'
        /// </summary>
        [Fact]
        public void FundedAmountTest()
        {
            // TODO unit test for the property 'FundedAmount'
        }
        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Fact]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }
        /// <summary>
        /// Test the property 'LoanAmount'
        /// </summary>
        [Fact]
        public void LoanAmountTest()
        {
            // TODO unit test for the property 'LoanAmount'
        }
        /// <summary>
        /// Test the property 'Sweep'
        /// </summary>
        [Fact]
        public void SweepTest()
        {
            // TODO unit test for the property 'Sweep'
        }
        /// <summary>
        /// Test the property 'CurrencyISOCode'
        /// </summary>
        [Fact]
        public void CurrencyISOCodeTest()
        {
            // TODO unit test for the property 'CurrencyISOCode'
        }

    }

}
