/* 
 * YouLend Third Party Pre Qualification API
 *
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Prequalification.Client.Api;
using YL.Web.Api.ThirdParty.Prequalification.Client.Model;
using YL.Web.Api.ThirdParty.Prequalification.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Prequalification.Client.Test
{
    /// <summary>
    ///  Class for testing PaymentDataRowModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentDataRowModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentDataRowModel
        //private PaymentDataRowModel instance;

        public PaymentDataRowModelTests()
        {
            // TODO uncomment below to create an instance of PaymentDataRowModel
            //instance = new PaymentDataRowModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentDataRowModel
        /// </summary>
        [Fact]
        public void PaymentDataRowModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaymentDataRowModel
            //Assert.IsInstanceOfType<PaymentDataRowModel> (instance, "variable 'instance' is a PaymentDataRowModel");
        }


        /// <summary>
        /// Test the property 'PaymentDate'
        /// </summary>
        [Fact]
        public void PaymentDateTest()
        {
            // TODO unit test for the property 'PaymentDate'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'CurrencyISOCode'
        /// </summary>
        [Fact]
        public void CurrencyISOCodeTest()
        {
            // TODO unit test for the property 'CurrencyISOCode'
        }

    }

}
