/* 
 * YouLend Third Party Pre Qualification API
 *
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Prequalification.Client.Api;
using YL.Web.Api.ThirdParty.Prequalification.Client.Model;
using YL.Web.Api.ThirdParty.Prequalification.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Prequalification.Client.Test
{
    /// <summary>
    ///  Class for testing PreQualificationModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PreQualificationModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PreQualificationModel
        //private PreQualificationModel instance;

        public PreQualificationModelTests()
        {
            // TODO uncomment below to create an instance of PreQualificationModel
            //instance = new PreQualificationModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PreQualificationModel
        /// </summary>
        [Fact]
        public void PreQualificationModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PreQualificationModel
            //Assert.IsInstanceOfType<PreQualificationModel> (instance, "variable 'instance' is a PreQualificationModel");
        }


        /// <summary>
        /// Test the property 'ThirdPartyMerchantId'
        /// </summary>
        [Fact]
        public void ThirdPartyMerchantIdTest()
        {
            // TODO unit test for the property 'ThirdPartyMerchantId'
        }
        /// <summary>
        /// Test the property 'Mid'
        /// </summary>
        [Fact]
        public void MidTest()
        {
            // TODO unit test for the property 'Mid'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'CompanyNumber'
        /// </summary>
        [Fact]
        public void CompanyNumberTest()
        {
            // TODO unit test for the property 'CompanyNumber'
        }
        /// <summary>
        /// Test the property 'CompanyType'
        /// </summary>
        [Fact]
        public void CompanyTypeTest()
        {
            // TODO unit test for the property 'CompanyType'
        }
        /// <summary>
        /// Test the property 'CompanyWebsite'
        /// </summary>
        [Fact]
        public void CompanyWebsiteTest()
        {
            // TODO unit test for the property 'CompanyWebsite'
        }
        /// <summary>
        /// Test the property 'ContactEmailAddress'
        /// </summary>
        [Fact]
        public void ContactEmailAddressTest()
        {
            // TODO unit test for the property 'ContactEmailAddress'
        }
        /// <summary>
        /// Test the property 'CountryISOCode'
        /// </summary>
        [Fact]
        public void CountryISOCodeTest()
        {
            // TODO unit test for the property 'CountryISOCode'
        }
        /// <summary>
        /// Test the property 'LoanCurrencyISOCode'
        /// </summary>
        [Fact]
        public void LoanCurrencyISOCodeTest()
        {
            // TODO unit test for the property 'LoanCurrencyISOCode'
        }
        /// <summary>
        /// Test the property 'SicCode'
        /// </summary>
        [Fact]
        public void SicCodeTest()
        {
            // TODO unit test for the property 'SicCode'
        }
        /// <summary>
        /// Test the property 'MccCode'
        /// </summary>
        [Fact]
        public void MccCodeTest()
        {
            // TODO unit test for the property 'MccCode'
        }
        /// <summary>
        /// Test the property 'MonthsTrading'
        /// </summary>
        [Fact]
        public void MonthsTradingTest()
        {
            // TODO unit test for the property 'MonthsTrading'
        }
        /// <summary>
        /// Test the property 'FinancialData'
        /// </summary>
        [Fact]
        public void FinancialDataTest()
        {
            // TODO unit test for the property 'FinancialData'
        }
        /// <summary>
        /// Test the property 'SignificantPersons'
        /// </summary>
        [Fact]
        public void SignificantPersonsTest()
        {
            // TODO unit test for the property 'SignificantPersons'
        }

    }

}
