/* 
 * YouLend Third Party Pre Qualification API
 *
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Prequalification.Client.Api;
using YL.Web.Api.ThirdParty.Prequalification.Client.Model;
using YL.Web.Api.ThirdParty.Prequalification.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Prequalification.Client.Test
{
    /// <summary>
    ///  Class for testing PreQualificationResultDocument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PreQualificationResultDocumentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PreQualificationResultDocument
        //private PreQualificationResultDocument instance;

        public PreQualificationResultDocumentTests()
        {
            // TODO uncomment below to create an instance of PreQualificationResultDocument
            //instance = new PreQualificationResultDocument();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PreQualificationResultDocument
        /// </summary>
        [Fact]
        public void PreQualificationResultDocumentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PreQualificationResultDocument
            //Assert.IsInstanceOfType<PreQualificationResultDocument> (instance, "variable 'instance' is a PreQualificationResultDocument");
        }


        /// <summary>
        /// Test the property 'ThirdPartyMerchantId'
        /// </summary>
        [Fact]
        public void ThirdPartyMerchantIdTest()
        {
            // TODO unit test for the property 'ThirdPartyMerchantId'
        }
        /// <summary>
        /// Test the property 'Mid'
        /// </summary>
        [Fact]
        public void MidTest()
        {
            // TODO unit test for the property 'Mid'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'OverallCreditRiskScore'
        /// </summary>
        [Fact]
        public void OverallCreditRiskScoreTest()
        {
            // TODO unit test for the property 'OverallCreditRiskScore'
        }
        /// <summary>
        /// Test the property 'OverrideCreditRiskScore'
        /// </summary>
        [Fact]
        public void OverrideCreditRiskScoreTest()
        {
            // TODO unit test for the property 'OverrideCreditRiskScore'
        }
        /// <summary>
        /// Test the property 'LoanOptions'
        /// </summary>
        [Fact]
        public void LoanOptionsTest()
        {
            // TODO unit test for the property 'LoanOptions'
        }

    }

}
