/* 
 * YouLend Third Party Pre Qualification API
 *
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Prequalification.Client.Api;
using YL.Web.Api.ThirdParty.Prequalification.Client.Model;
using YL.Web.Api.ThirdParty.Prequalification.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Prequalification.Client.Test
{
    /// <summary>
    ///  Class for testing PurchaseDataRowModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PurchaseDataRowModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PurchaseDataRowModel
        //private PurchaseDataRowModel instance;

        public PurchaseDataRowModelTests()
        {
            // TODO uncomment below to create an instance of PurchaseDataRowModel
            //instance = new PurchaseDataRowModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PurchaseDataRowModel
        /// </summary>
        [Fact]
        public void PurchaseDataRowModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PurchaseDataRowModel
            //Assert.IsInstanceOfType<PurchaseDataRowModel> (instance, "variable 'instance' is a PurchaseDataRowModel");
        }


        /// <summary>
        /// Test the property 'PurchaseDate'
        /// </summary>
        [Fact]
        public void PurchaseDateTest()
        {
            // TODO unit test for the property 'PurchaseDate'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'CurrencyISOCode'
        /// </summary>
        [Fact]
        public void CurrencyISOCodeTest()
        {
            // TODO unit test for the property 'CurrencyISOCode'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }

    }

}
